channel19/channel19/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('chat.urls')),
    path('admin/', admin.site.urls),
]

channel19/chat/urls.py
from django.urls import path

from . import views

app_name = 'chat'
urlpatterns = [
    path('', views.index, name='index'),
    path('cb/<str:room_uuid>', views.instance, name='instance'),
    path('new/', views.generate, name='generate'),
    path('cb/<str:room_uuid>/get_active', views.fetch_active, name='fetch_active'),
    path('cb/<str:room_uuid>/get_seconds_to_expiry', views.get_seconds_to_expiry, name='get_seconds_to_expiry'),
    path('about', views.about, name='about'),
    path('swag', views.swag, name='swag'),
    path('cb/<str:room_uuid>/get_available_username', views.get_available_username, name='get_available_username'),
]

channel19/chat/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.utils.crypto import get_random_string
from django.conf import settings
from django.utils import timezone
import random 


def idgen():
    import string
    all_chars = string.digits + string.ascii_letters
    all_chars = all_chars.replace("l", '') #remove the lowercase L (l) because it can be confused with uppercase I 
    return get_random_string(6, all_chars)

def name_gen():
    return f"user_{idgen()}"


NAME_CHOICES = (
('John','John'),
('Paul', 'Paul'),
('George','George'),
('Ringo','Ringo'),
)

class Room(models.Model):

    def __str__(self):
        return self.uuid

    uuid = models.CharField(max_length=30, default=idgen)
    creation_date = models.DateTimeField(auto_now_add=True)


class Talker(models.Model):

    def __str__(self):
        return (f'Room: {self.room} - User: {self.guid}')

    def choose_random_name():
        return random.choice(NAME_CHOICES)[1]

    guid = models.CharField(max_length=30, default=name_gen)
    creation_date = models.DateTimeField(auto_now_add=True)
    identifier = models.CharField(max_length=100, null=True, blank=True)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    talker_name = models.CharField(max_length=7, choices=NAME_CHOICES, default=choose_random_name)

    class Meta:
        unique_together = ['room', 'talker_name']

    def save(self, *args, **kwargs):
        max_children = settings.MAX_USERS_PER_ROOM
        if self.room and self.pk is None:
            children = Talker.objects.filter(room=self.room)
            if children.count() >= max_children:
                raise ValidationError('A parent can only have a maximum of {} children.'.format(max_children))
        super().save(*args, **kwargs)


# class Listener(models.Model):
#     def __str__(self):
#             return self.guid

#     guid = models.CharField(max_length=30, default=name_gen)
#     creation_date = models.DateTimeField(auto_now_add=True)
#     identifier = models.CharField(max_length=100, null=True, blank=True)
#     room = models.ForeignKey(Room, on_delete=models.CASCADE)

channel19/chat/views.py
from django.shortcuts import render
from chat.models import Room
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.http import JsonResponse
from django.conf import settings 
import random
from django.utils import timezone


def generate(request):
    new_rm= Room()
    new_uuid = new_rm.uuid
    new_rm.save()
    return HttpResponseRedirect(reverse('chat:instance', args=(new_uuid,)))


def fetch_active(request, room_uuid):
    try:
        room = Room.objects.get(uuid=room_uuid)
        number_of_talkers = len(room.talker_set.all())
    except Room.DoesNotExist:
        return render(request, 'chat/404.html')
    context = {'room_name': room_uuid,
            'talker_count': number_of_talkers}
    return JsonResponse(context)

def get_available_username(request, room_uuid):
    try:
        room = Room.objects.get(uuid=room_uuid)
        number_of_talkers = len(room.talker_set.all())
        if number_of_talkers >= settings.MAX_USERS_PER_ROOM:
            context = {'room_name': room_uuid}
            return render(request, 'chat/room_full.html', context=context)
    except Room.DoesNotExist:
        return render(request, 'chat/404.html')
    
    names = ['John', 'Paul', 'George', 'Ringo']
    random.shuffle(names) #shuffle in place
    recommended_name="not_sure"
    for name in names:
        if len(room.talker_set.filter(talker_name=name)) == 0:
            recommended_name = name
    context = {'room_name': room_uuid,
            'recommended_name': recommended_name}
    return JsonResponse(context)

def index(request):
    template_name = 'chat/index.html'
    return render(request, template_name)


def about(request):
    template_name = 'chat/about.html'
    return render(request, template_name)

def swag(request):
    template_name = 'chat/swag.html'
    return render(request, template_name)

def get_seconds_to_expiry(request, room_uuid):
    try:
        room = Room.objects.get(uuid=room_uuid)
        seconds_to_expiry = calculate_seconds_to_expiry(room)
        if seconds_to_expiry < 0: #the room is expired
            return render(request, 'chat/404.html')
    except Room.DoesNotExist:
        return render(request, 'chat/404.html')
    context = {'room_name': room_uuid,
            'seconds_to_expiry': seconds_to_expiry}
    return JsonResponse(context)

def calculate_seconds_to_expiry(room):
    now = timezone.now()
    cre = room.creation_date
    maximum_life_of_room = settings.SECONDS_FOR_ROOM_EXISTENCE #900 seconds as of now 
    room_has_been_active = (now - cre).seconds #how long the room has existed
    if room_has_been_active > maximum_life_of_room: #if room has been active longer than it should
        return -1
    else:
        return maximum_life_of_room - room_has_been_active #return total life - life_used IE return seconds to death 

    
def instance(request, room_uuid):
    print('in instance')
    try: 
        room = Room.objects.get(uuid=room_uuid)
        if calculate_seconds_to_expiry(room) < 0:
            context = {'room_name': room.uuid}
            return render(request, 'chat/404.html', context=context)
        number_of_talkers = len(room.talker_set.all())
        if number_of_talkers >= settings.MAX_USERS_PER_ROOM:
            context = {'room_name': room_uuid}
            return render(request, 'chat/room_full.html', context=context)
    except Room.DoesNotExist:
        return render(request, 'chat/404.html')
    context = {'room_name': room_uuid,
            'talker_count': number_of_talkers,
            'created': room.creation_date}
    return render(request, 'chat/room.html', context=context) 

channel19/channel19/templates/chat/index.html
<h1>Welcome to the home page</h1>
<br/>



<form action="{% url 'chat:generate' %}" method="post">
    {% csrf_token %}
    <input type="submit" value="Generate Room!">
</form>

channel19/channel19/templates/chat/room.html
<html>
<head>
    <meta charset="utf-8"/>
    <h1>You made it to Room #{{ room_name }}</h1>
</head>
<body>
    <textarea id="chat-log" cols="100" rows="20"></textarea><br>
    <input id="chat-message-input" type="text" size="100"><br>
    <input id="chat-message-submit" type="button" value="Send">
    {{ room_name|json_script:"room-name" }}
    <script>
        const roomName = JSON.parse(document.getElementById('room-name').textContent);

        const chatSocket = new WebSocket(
            'ws://'
            + window.location.host
            + '/ws/chat/'
            + roomName
            + '/'
        );

        chatSocket.onmessage = function(e) {
            const data = JSON.parse(e.data);
            document.querySelector('#chat-log').value += (data.message + '\n');
        };

        chatSocket.onclose = function(e) {
            console.error('Chat socket closed unexpectedly');
        };

        document.querySelector('#chat-message-input').focus();
        document.querySelector('#chat-message-input').onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#chat-message-submit').click();
            }
        };

        document.querySelector('#chat-message-submit').onclick = function(e) {
            const messageInputDom = document.querySelector('#chat-message-input');
            const message = messageInputDom.value;
            chatSocket.send(JSON.stringify({
                'message': message
            }));
            messageInputDom.value = '';
        };
    </script>
</body>
</html>

channel19/chat/templates/chat/about.html
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Channel 42</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/about.css' %}">
    <meta property="og:title" content="Channel 42" />
    <meta property="og:description" content="Check this out: Channel 42" />
    <meta property="og:image" content="{% static 'img/square-logo.png' %}" />
</head>
<link rel="icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}">
<div class="tiny-top-bar">
    <div class="top-button-div-el">
        <a href="/" class="top-bar-button">Home</a>
    </div>
</div>
    <div class="center-main-container">
        <div class="logo-row-box">
                <img class='image-logo' src="{% static 'img/logo_white-min.png' %}" alt="">
        </div>
        <div class="main-content-box">
            <h1 class='about-title'>About.</h1>
            <div class="about-page-main-div">
                <p class="about-page-text">

                    Hey everyone, 
                    <br>
                    <br>

                    I am a long-time redditor and a law student who likes to procrastinate by building software things. I have been working on this side project for a couple months and am happy to finally
                    release it into the wild. 
                    <br><br>

                    Welcome to Channel 42. 
                </p>
                <h2 class="about-h2">
                    What is Channel 42?
                </h2>

                <p class="about-page-text">
                    Channel 42 is a temporary, disposable, authentication-free voice chat platform built to make reddit better. 
                    
                    <br><br> 
                    It's ease of use was inspired by Imgur (another for-reddit-by-reddit project). 
                    <br><br> 
                    
                    
                    Go to the site, create a subchannel, and share the URL. It's that simple. 
                    <br><br> 
                    Anyone with the link is connected automatically.
                    <br><br> 
                    The roooms are capped at four participants and expire after two hours. 
                    <br><br>
                </p>
                <h2 class="about-h2">
                    What is Channel 42 for?
                </h2>

                <p class="about-page-text">
                    Reddit is really good at bringing people with common interests together, it does an awesome job of connecting us
                     - but once we've found someone we want to go back-and-forth with, a message board isn't always the best medium for efficient communication. 
                     Sometimes its easier to just talk. 
                     
                    <br><br> 
                    But you don't always want to share 
                    your personal info (socials, email, phone, discord, etc.) with someone just so that you can chat with them for a few minutes. It's unneccessary. This is where Channel 42 comes in.
                    <br><br>
                    Reddit has already done the hard part: helping us connect with others who share our interests - Channel 42 is just another communication layer that can be used when needed. 
                    <br><br> 
                    Whether it is an earnest debate in r/changemyveiw 
                    or an expert in a niche sub explaining something like you are 5, Channel 42 can be a great way to exchange ideas quickly and easily in a variety of contexts. 
                </p>
                <h2 class="about-h2">
                    How does Channel 42 work?
                </h2>
                <p class="about-page-text">
                    Clicking "Generate Subchannel" on the home page will bring you to a brand new subchannel. You can click "Copy Room URL" (or just grab it from the URL bar in the browser) and then share that link. 
                    
                    You can share links via DM, or post them publicly right into a reddit thread. How you share them is up to you. Anyone with the link can enter the room and join the conversation (unless the room is full).
                    <br><br>
                    Because there is no traditional Auth, you should be mindful about where you share a link, depending on your goals. The rooms are capped at four participants because voice can get messy with too many people.
                    This is something that could change in future releases. 
                    <br><br>
                    When links are posted publicly, trolls may infiltrate. How to handle that is up to you, but remember you can always ditch the channel and make a new one, sharing by DM for example. 
                    <br><br>
                    My hope is that some public links will be useful, perhaps because they will be burried deep into comment sections such that only interested users would venture that far down and stumble across them. 
                    I will be interested to see how the uses of Channel 42 develop. Its designed for reddit but maybe it would be good on StackOverflow, or for gaming. Time will tell. 
                    <br><br>
                    Because the subchannels only last for a couple hours, subreddits will probably want a moderator bot to auto-delete Channel 42 links that are older than that amount of time, 
                    so that comment sections don't get littered with stale links. 
                    I haven't ever made an auto-mod bot before, but if this becomes a problem I will be happy to contribute and/or write one. 
                    <br><br>
                    If you would like to chat longer than 2 hours you can: A) make a new subchannel or B) exchange info and chat on another platform. 
                    Its totally up to you. Channel 42 is the Citizens' Band. 
                </p>
                <h2 class="about-h2">
                    Why "42"?
                </h2>

                <p class="about-page-text">
                    It is the meaning of life. And the domain was available.
                    <br><br>
                </p>

                <h2 class="about-h2">
                    What is a shareport?
                </h2>

                <p class="about-page-text">
                    Channel 42 is for voice chatting, but I wanted to give people a way to share links during their conversation if they need to. 
                    So I came up with the shareport. It has just one input and one output. 
                    <br><br>
                    Send a link outbound to the rest of the room, or copy an inbound link to your clipboard. 
                    
                </p>

                <h2 class="about-h2">
                    What's the stack?
                </h2>
                <p class="about-page-text">
                    Channel 42 uses webRTC (Google's open-source media streaming library) to setup p2p (peer-to-peer) connections between users in a room, resulting in a decentralized "Mesh" architecture. All connections are end-to-end encrypted.  
                    <br><br>
                    Because it creates p2p connections, Channel 42 may not work with some VPNs, or may take a long time to connect through a VPN. That is a tradeoff I made. I am open to other architectures in the future if there is demand, but this is version 1.
                    <br><br>
                    Channel  42 runs on a vanilla Javascript frontend, and Python (Django) on the server side. Signaling is done using websockets. I wrote everything myself with help from many sources online. 
                    All bugs are my own.
                    <br><br>
                    Channel 42 has been a labor of love. This is definitely the most ambitious software project I have worked on, and a lot of elbow grease has gone into it. It's been fun and I have learned a ton. 
                    The logo is based on an old CB (Citizens' Band) Radio, and I made it in photoshop. 
                </p>

                <h3 class="about-h3">
                    Bugs? Questions? Comments?
                </h3>
                <p class="about-page-text contact-p">
                    reachout.channel42@gmail.com
                </p>

            </div>
        </div>
    </div>

channel19/chat/templates/chat/index.html
<!DOCTYPE html>

<!-- Block elements stack up on top of one another
and fill the available width of the browser window or other containing element. 
Inline elements and text characters line up next to one another to fill
the block elements. 

EM: Relative to the parent element

REM: Relative to the root element (HTML tag)

%: Relative to the parent element

VW: Relative to the viewport’s width

VH: Relative to the viewport’s height


-->
<html lang="en">
    {% load static %}
<head>
    <meta charset="UTF-8">
    <title>Channel 42</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">
    <link rel="icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta property="og:title" content="Channel 42" />
    <meta property="og:type" content="website" />
    <meta property="og:description" content="Channel 42 - Home" />
    <meta property="og:image" content="{% static 'img/square-logo.png' %}" />
    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:title" content="Channel 42" />
    <meta name="twitter:description" content="Channel 42 - Home" />
    <meta name="twitter:image" content="{% static 'img/square-logo.png' %}" />
</head>
<body>
    <nav class="tiny-top-bar">
        <div class="top-bar-button">
            <a href="/about" class="about-button">About</a>
        </div>
        <div class="top-bar-button">
            <a href="/swag" class="about-button">Swag</a>
        </div>
        
    </nav>
    <div class="center-main-container">
        <div class="logo-box">
            <img src="{% static 'img/logo_white-min.png' %}" alt="">
        </div>
        <div class="button-box">
            <div class="form-div">
                <form class="button-form" action="{% url 'chat:generate' %}" method="post">
                    {% csrf_token %}
                    <input class="generate-button" type="submit" value="Generate Subchannel">
                </form>
            </div>
        </div>
    </div>
    
</body>
</html>

channel19/chat/templates/chat/room.html
<!DOCTYPE html>

{% load static %}

<html lang="en" id="whole-page">
    <link rel="icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}">
    <head>
        <meta charset="UTF-8">
        <script>history.scrollRestoration = "manual"</script>
        <title>Channel 42</title>
        <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta property="og:title" content="Channel 42" />
        <meta property="og:description" content="Meet me on Channel 42" />
        <meta property="og:image" content="{% static 'img/square-logo.png' %}" />
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content="Channel 42" />
        <meta name="twitter:description" content="Meet me on Channel 42" />
        <meta name="twitter:image" content="{% static 'img/square-logo.png' %}" />
        
    </head>
    <body>
        <nav class="tiny-top-bar">
                <div class="top-bar-button"><a id='home-btn' href="/" class="top-bar-button">Home</a></div>
                <div class="top-bar-button"><a href="/about" class="top-bar-button">About</a></div>
        </nav>
        <div class="center-main-container">
            <div class="logo-box-top">
                    <img id='main-logo-image' class='main-logo-img' src="{% static 'img/logo_white-min.png' %}" alt="">
            </div>
            <div id="side-car-div">
                <div class="data-box-middle-row">
                    <table class="data-table">
                        <tbody>
                            <tr>
                                <td>Subchannel URL:</td>
                                <td>........</td>
                                <td class="table-data-end">{{room_name}}</td>
                            </tr>
                            <tr>
                                <td>Version:</td>
                                <td>......</td>
                                <td class="table-data-end">1.01</td>
                            </tr>
                            <tr>
                                <td>Conn. Status:</td>
                                <td>......</td>
                                <td class="table-data-end" id="basic-conn-status">Working..</td>
                            </tr>
                            <!-- <tr>
                                <td>Active Users (DB):</td>
                                <td>......</td>
                                <td class="table-data-end" id="connected-user-count-db">X</td>
                            </tr> -->
                            <!-- <tr>
                                <td>#Active(JS):</td>
                                <td>......</td>
                                <td class="table-data-end"  id="connected-user-count-js">X</td>
                            </tr> -->
                            <tr>
                                <td>Users Present:</td>
                                <td>......</td>
                                <td class="table-data-end" id="connected-user-count-dc">X</td>
                            </tr>
                            <tr>
                                <td>Max Users:</td>
                                <td>......</td>
                                <td class="table-data-end">4</td>
                            </tr>
                            <tr>
                                <td>Expires in:</td>
                                <td>......</td>
                                <td class="table-data-end" id="expiry_clock">^Loading</td>
                            </tr>
                            <!-- <tr>
                                <td>JS time Now:</td>
                                <td>......</td>
                                <td class="table-data-end" id="time-now">^Loading</td>
                            </tr>
                            <tr>
                                <td>difference:</td>
                                <td>......</td>
                                <td class="table-data-end" id="diff-now">^Loading</td>
                            </tr> -->
                            <tr>
                                <td>You are:</td>
                                <td>......</td>
                                <td id="user-username" class="table-data-end">TEMP</td>
                            </tr>
                            <tr>
                                <td>Also connected:</td>
                                <td></td>
                                <td></td>
                            </tr>
                            <tr>
                                <td></td>
                                <td>
                                    <ul id="dummy-peer-list">
                                        <li></li>
                                        <li></li>
                                        <li></li>
                                    </ul>
                                </td>
                                <td id="peer-table-row" class="table-data-end">
                                    <ul id="connected-peer-list">
                                    </ul>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                   
                </div>
                <div class="bottom-box-controls-row">
                    <div class="div-lower-button"><button class="control-button control-button-mute" id="btn-toggle-audio">  Mute Mic</button>  </div>
                    <div class="div-lower-button"><button onclick=disconnectUser() class="control-button control-button-disconnect" id="btn-disconnect"</button> Disconnect </div>
                    <div class="div-lower-button"><button class="control-button control-button-copy" id="btn-copy-link"><img id='link-logo-img' src="{% static 'img/link-img9.png' %}"/>Copy Room URL</button>  </div>
                    <div class="div-lower-button"><button class="control-button control-button-copy" id="new-peer-button">Reset Connection</button></div>
                    <div class="div-lower-button switch-box">
                        <div class="switch-label-box">
                            <text class="switch-label-text">Play sound on join:</text>
                        </div>
                        <label class="switch">
                            <input id="alert-input" type="checkbox" autocomplete="off">
                            <span class="slider round"></span>
                        </label>
                    </div>
                    <div id="toggle-chat-switch" class="div-lower-button switch-box">
                        <div class="switch-label-box">
                            <text class="switch-label-text">Toggle Shareport:</text>
                        </div>
                        <label class="switch">
                            <input id="toggle-chat-input" type="checkbox" autocomplete="off">
                            <span class="slider round"></span>
                        </label>
                    </div>
                    
                </div>
                <div id="chat-main" class="hidden">
                    <div id="messages" class="io-box">
                        <input readonly id="message-content-text" class="io-input" placeholder="INBOUND"></input>
                        <div class="input-box-extras">
                            <div id="sender-id-box">
                                <p style='margin: 0;' id='sender-title'></p>
                            </div>
                            
                            <button class="io-button control-button control-button-send-outbound" id="btn-copy-msg"><img id='link-logo-img' src="{% static 'img/link-img9.png' %}"/>Copy</button>
                        </div>

                    
                        <!-- <p id="message-content-p">Content of messageContent of messageContent of messageContent of messageContent of messageContent of messageContent of messageContent of messageContent of messageContent of messageContent of messageContent of messageContent of message</p> -->
                    </div>
                    <div id="outgoing-box" class="io-box">
                        <input id="msg" class="io-input" placeholder="OUTBOUND"></input>
                        <button class="io-button control-button control-button-copy-inbound" id="btn-send-msg">Send<img id='link-logo-img' style='margin-left:5px' src="{% static 'img/send-logo2.png' %}"/></button>
                    </div>
                       
                    
                </div>
                <div id="talking-test"></div>

            </div>
            
           

            <div class="audio-container">
                <audio id='local-audio' autoplay playsinline></audio>
            </div>
            <audio id="new-peer-joining-sound">
                <source src="{% static 'img/entrance_sound.mp3' %}" type="audio/mpeg">
            </audio>
        </div>
    </body>
    <script type="text/javascript" src="{% static 'js/main.js' %}"></script>
    <link rel="prefetch" href="{% static 'img/logo_white-red-min.png' %}">


</html> 

channel19/chat/templates/chat/room_full.html
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Channel 42</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/room_full.css' %}">
    <meta property="og:title" content="Channel 42" />
    <meta property="og:description" content="Meet me on Channel 42" />
    <meta property="og:image" content="{% static 'img/square-logo.png' %}" />
</head>
<link rel="icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}">
<div class="tiny-top-bar">
    <div class="top-button-div-el">
        <a href="/" class="top-bar-button">Home</a>
    </div>
</div>
<div class="center-main-container">
    <div class="logo-row-box">
        <img class='image-logo' src="{% static 'img/logo_white-min.png' %}" alt="">
    </div>
    <div class="main-content-box">
        <h1 class='title-four-o-four'>Room Full.</h1>
        <div class="about-page-main-div">
            <div class="chunky-div">
                <img class="chunky-img" src="{% static 'img/office.png' %}" alt="">
            </div>
            <div class="text-div">
                <p class='p-404'>This Room is at capacity. Try back later, or: <br><br><a href="../">Generate a new one here.</a> </p>
            </div>
            
        </div>
    </div>
</div>

channel19/chat/templates/chat/swag.html
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Channel 42</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/swag.css' %}">
    <meta property="og:title" content="Channel 42" />
    <meta property="og:description" content="Check out this Channel 42 Swag" />
    <meta property="og:image" content="{% static 'img/square-logo.png' %}" />
</head>
<link rel="icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}">
<div class="tiny-top-bar">
    <div class="top-button-div-el">
        <a href="/" class="top-bar-button">Home</a>
    </div>
</div>
<div class="center-main-container">
    <div class="logo-row-box">
        <img class='image-logo' src="{% static 'img/logo_white-min.png' %}" alt="">
    </div>
    <div class="main-content-box">
        <h1 class='title-four-o-four'>Swag.</h1>
        <div class="about-page-main-div">
            <div class='overall-item-div'>
                <div class="swag-div">
                    <img class="chunky-img" src="{% static 'img/sweatshirt.png' %}" alt="">
                </div>
            </div>
            
            <div class="text-div">
                <p class='p-404'>Sweatshirts on preorder. $40 + Shipping. Sign up <a href="https://forms.gle/robZozkwgH7FbGj77">here</a></p>
            </div>
            <div class="text-div">
                <p class='p-404'>Sending free stickers to first 100 people to email me. Address on "about" page (scroll all the way down).</p>
            </div>
            <div class="text-div">
                <p class='p-404'>Enjoy the service? Become a Patron: <a href="https://patreon.com/purplefloyd?utm_medium=clipboard_copy&utm_source=copyLink&utm_campaign=creatorshare_creator&utm_content=join_link">Patreon</a> </p>
            </div>
        </div>
    </div>
</div>